### ISSUE TITLE
Fix minor code and doc issues

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar-i18n-control#1]
- [ ] line 46: add braces to arrow function body, since the assignment should not return anything
- [ ] line 56ff: add documentation for return value and cleanup parameter documentation
- [ ] line 84: simplify method call using array spread operator
   `formatter.format.apply( formatter, [ i18nValue, args ] )` => 
   `formatter.format( ...[ i18nValue, args ] )`

**Comment by x1B** [comment]
_Closed:_ repository is obsolete
